export default {
  namespaced: true,
  state: () => ({
    muscles: {
      0: "biceps",
      1: "deltoids",
      2: "forearms",
      3: "triceps",
      4: "trapezius",
      5: "lats",
      6: "abs",
      7: "obliques",
      8: "pectorals",
      9: "adductors",
      10: "calves",
      11: "hamstrings",
      12: "glutes",
      13: "quads",
    },
    foodTypes: {
      0: "Vegetables",
      1: "Fruits",
      2: "Seafood",
    },
    workoutLevels: {
      0: "Beginner",
      1: "Intermediate",
      2: "Advanced",
    },
    days: {
      0: "Sunday",
      1: "Monday",
      2: "Tuesday",
      3: "Wednesday",
      4: "Thursday",
      5: "Friday",
      6: "Saturday",
    },
    exerciseTypes: {
      0: "Cardio",
      1: "Weight lifting",
    },
  }),
  mutations: {},
  actions: {},
  getters: {},
};
